---

- name: ensure gpg2 is installed on Debian Stretch and Ubuntu 18.04
  apt:
    pkg: gnupg2
    state: present
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 9) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 18)

- name: Ensure apt_preferences include file for deb.torproject.org is present
  copy:
    src: apt/preferences.d/deb.torproject.org.pref
    dest: /etc/apt/preferences.d/deb.torproject.org.pref
    mode: 0644
    owner: root
    group: root

# required to allow installation of packages from torproject repo
- name: ensure the repository key is present
  apt_key:
    data: "{{ lookup('file', 'torproject.asc') }}"
    state: "{{ onion_tor_apt_state }}"
    id: "{{ onion_tor_apt_key_id }}"

- name: ensure the required repository is present
  apt_repository:
    repo: "deb {{ 'https' if ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 10 else 'http' }}://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main"

- name: install extra tor packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ onion_apt_packages }}"

- set_fact:
    tor_user: "{{ onion_tor_user or 'debian-tor' }}"
- set_fact:
    tor_group: "{{ onion_tor_group or 'debian-tor' }}"
